### PR TITLE
Implement a plugin for Cloudflare v4 API.

### PR DESCRIPTION
**Pull request by mmannerm**
Implement a cloudflare.com plugin that supports both A and AAAA records. Requires IP address to be given, so does not work with the ip-disabled plugin. Creates a new record if one does not exist already.

Cloudflare v4 API documentation: https://api.cloudflare.com

### CODE REVIEW

**Comment by leamas** [comment]
Hm... this is an impressing work, thanks for the PR.  Cloudflare is obviously far more complicated than any existing plugin.

I think you need to check if the  zone option is available in opts before using it. Example code in ip_from_cmd plugin. Otherwise it  looks great.

**Comment by mmannerm** [comment]
Added check for zone option.

Cloudflare is not really a dynamic dns provider, but since there is support for DNS01 challenge in ACME spec (letsencrypt), and certificate-manager/certbot support it out of the box, and it has a free tier for single personal domain, I find it quite useful.

**Comment by leamas** [comment]
Again: thanks for your contribution!

**Comment by mmannerm** [comment]
No problem, hopefully we will see this soon released. Thank you for doing such an useful utility, and choosing python, as my perl skills are not that great on fixing the ddclient :)

**Pull request merged**
