### PR TITLE
New plugin domains.google.com

### LINKED ISSUE #15: RFE: Add support for google domains
https://support.google.com/domains/answer/6147083?hl=en

### PR DESCRIPTION
**Pull request by LoganK**
Closes #15

### CODE REVIEW

**Comment by leamas** [comment]
hmm.. Thanks for taking care of this, most welcome!

While we are on it: Could you please add some error checking? Basically, take the return value from `get_response()`and log an error if it's not OK. There are plenty of examples in other plugins.

**Comment by LoganK** [comment]
Absolutely. Update soon.

**Comment by LoganK** [comment]
I split it into two different pull requests so there could be consistent logging and error checking across similar plugins. Please take a look at #33 first.

**Comment by leamas** [comment]
hm... actually, I'm not really fond of this. Adding server-specific code to ddplugin should not be done lightly, and here I cannot see that the advantages (less duplication) justifies expanding ddplugin.

In short: Could you update the requests by simply duplicating this code in the two service plugins without touching ddplugin I would happily merge them both.

**Comment by LoganK** [comment]
Code duplicated across plugins.

**Comment by leamas** [comment]
hm... is it? Have you forgot to push something? Or do I miss something else? I see just the old code calling`check_dyndns_response()`?!

**Comment by LoganK** [comment]
Blergh, sorry about that. The changes got stuck in the index.

**Comment by leamas** [comment]
No problem ;)  

All looks fine. I have  merged this into the devel branch. This is the new default branch, master is from now on basically just the released stuff.

Again: many thanks for taking care of this. Closing

**Pull request closed without merging**
